language: python
python:
  - "2.7"
cache: pip
before_install:
  - sudo rm -f /etc/boto.cfg
install:
  - python setup.py install
  - pip install -r requirements-dev.txt
script:
    - nosetests --exclude-dir="test/disco_tests"
